// <auto-generated />
namespace eCommerce.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changevouchertypeidtoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changevouchertypeidtoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201501060917408_changevouchertypeidtoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
